resolver: lts-18.27

packages:
- .

extra-deps:
  - git: https://github.com/primetype/inspector
    commit: c39d899e29acb8e37d58618ae3bf80aabf13d23c

  - git: https://github.com/input-output-hk/cardano-crypto
    commit: 07397f0e50da97eaa0575d93bee7ac4b2b2576ec
